version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      - POSTGRES_DB=teamup_users_core
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - app-network

  users:
    build:
      context: .
      dockerfile: users/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=teamup_users_core
      - DB_USER=postgres
      - DB_PASSWORD=1234
    depends_on:
      - db
    networks:
      - app-network

  core:
    build:
      context: .
      dockerfile: core/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=teamup_users_core
      - DB_USER=postgres
      - DB_PASSWORD=1234
    depends_on:
      - db
      - users
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
