logging:
  level:
    org.example.exceptions: ERROR
    org.springframework.security: DEBUG
    org.springframework.web.filter: DEBUG

server:
  port: 8081
spring:
  application:
    name: core-service
  profiles:
    active: prod
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
  security.enable_csrf: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://core_db:5432/teamup_users_core
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: core
        show_sql: true
    open-in-view: false
    generate-ddl: true

